### ISSUE TITLE
Bearbeitungsdauer umstellen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle_local_adele#192]
- [ ] Umbau Zeiteinschätzung ("Estimated duration") zu: Eingabefeld int, Select für Zeitspanne: Min, Stunden, Tage.
    - [ ] Zusatzfelder für Lernpfadsetting: 
        - [ ] "Standardbearbeitungsdauer einer Node": selbes Eingabefeld und Select für Zeitspanne siehe oben
        - [ ] Checkbox: "Verwende Standardbearbeitungsdauer zur Darstellung der verbleibenden Dauer" + TikTak Symbol Anzeige als Beispiel. 
        - [ ] Info: Zur Berechnungslogik. 
        - [ ] Berechnungslogik für Version 1.0:  Wenn die angegebene Bearbeitungsdauer noch mind. 30x zur Verfügung steht Striche im 1. drittel), 30 < 2. Drittel > 5 und 5 > letztes Drittel. 

Für spätere Versionen vorgesehen: Bearbeitungsdauer wird multipliziert mit Strichen des Symbols.

**Comment by WunderJacob** [comment]
- [ ] Adminsettings (checkbox und time+select(Pflicht!))
- [ ]  'restliche Zeit' dividiert durch Estimated duration in node => tik-tak Striche abgezogen (24-Striche)

**Comment by eynimeni** [comment]
outdated
