### ISSUE TITLE
Punkte, Zusatzpunkte etc. in der Listenansicht

### ISSUE THREAD

**Issue by fabianplate** [Wunderbyte-GmbH/moodle_local_adele#220]
![Image](https://github.com/user-attachments/assets/60c41a5d-5112-46ac-89c1-f4e3ab95b9b1)

Folgender Text besteht aus meiner Mitschrift in der Besprechung mit Carolin. So ist der Text nicht eindeutig bzw. vollständig.
Muss von uns aktualisiert werden.

_So ist es unlogisch. Wir visieren statt Knoten ein Punktekonzept an. Punkte für abgeschlossene Knoten, und Punkte je nach Güte, Prio-Stufe.   Idee: Zusatzpunkte für Abschluss über dem Mindestmaß, optionale_

**Comment by fabianplate** [comment]
- [ ] Der Dozent kann bei der Erstellung des LP den Nodes einen Basispunktewert zuweisen. 
Diese Punkte bekommen die Lernenden bei bestehen des Kurses gutgeschrieben. Wenn der Dozent nichts zuweist, gibt der Kurs keine Punkte. Es ist möglich, dass manche Kurse Punkte geben und manche nicht.

- [ ] Je nach Gütestufe des Abschlusses wird der Basiswert mit einem Faktor multipliziert. Die Faktoren sind:
x.x (Prio 1)
x.x (Prio 2)
x.x (Prio 3)
x.x (Prio 4)
Muss offensichtlich noch geklärt werden.

**Comment by fabianplate** [comment]
Wir unterscheiden zwischen **Basispunkten** und **Zusatzpunkten**.
Basispunkte gibt es für den primären Abschluss. Also egal auf welchem Weg der Kurs abgeschlossen wird. 
Zusatzpunkte gibt es für zusätzlichen Aufwand nach dem primären Abschluss. Also das Nachholen der Bearbeitung oder eines Tests.

**Beispiele:**
P1 kann keinen Test vorweisen und bearbeitet den Kurs. P1 erhält den Basiswert (bspw. 50 Punkte) und die höchsten Zusatzpunkte (bspw. auch 50 Punkte) für die Bearbeitung. Danach macht/wiederholt P1 noch freiwillig den Test und bekommt dafür die zweithöchsten Zusatzpunkte (bspw. 30). **Endergebnis -> 50 + 50 + 30 = 130**


P2 hat den Test bestanden und damit abgeschlossen. P2 Basiswert (bspw. 50 Punkte) und die zweithöchsten Zusatzpunkte (bspw. 30)
P2 macht jetzt die Bearbeitung und bekommt 50 ZP dafür ->**Endergebnis -> 50 + 30 + 50 = 130**

So erhalten am Ende alle Nutzer für den gleichen Aufwand die gleichen Punkte, im Zwischenstand sieht es aber noch unterschiedlich aus.

Für die Punkte des manuellen Abschlusses soll eine Eingabemaske für den LP-Ersteller geben. Vorschlag: Im Feedbackfenster beim Definieren der Abschlussbedingungen. 
Der Defaultwert sollte 0 sein, da der manuelle Abschluss keine ZP geben sollte, wenn er als "letzte Lösung" gedacht ist.
Bei besonderen, aufwändigen Leistungen wie Praktika, Hausarbeiten etc. kann der Dozent dann natürlich entsprechend hohe Werte eingeben.

**Comment by WunderJacob** [comment]
Ich schätze den Aufwand auf 20 Stunden mindestens. Kleiner Userflow-Fehler:
_P1 kann keinen Test vorweisen und bearbeitet den Kurs. P1 erhält den Basiswert (bspw. 50 Punkte) und die höchsten Zusatzpunkte (bspw. auch 50 Punkte) für die Bearbeitung. Danach macht/wiederholt P1 noch freiwillig den Test und bekommt dafür die zweithöchsten Zusatzpunkte (bspw. 30). Endergebnis -> 50 + 50 + 40 = 50 + 90_
Hier wird der Student nach dem Abschliessen des Kurses durch Bearbeitung nicht mehr den Test sehen in der Node, da dieser minderwertiger ist.

**Comment by fabianplate** [comment]
> Ich schätze den Aufwand auf 15 Stunden mindestens. Kleiner Userflow-Fehler: _P1 kann keinen Test vorweisen und bearbeitet den Kurs. P1 erhält den Basiswert (bspw. 50 Punkte) und die höchsten Zusatzpunkte (bspw. auch 50 Punkte) für die Bearbeitung. Danach macht/wiederholt P1 noch freiwillig den Test und bekommt dafür die zweithöchsten Zusatzpunkte (bspw. 30). Endergebnis -> 50 + 50 + 40 = 50 + 90_ Hier wird der Student nach dem Abschliessen des Kurses durch Bearbeitung nicht mehr den Test sehen in der Node, da dieser minderwertiger ist.

Ahja, richtig. Ich hatte erst ein beliebiges Beispiel gemacht, dann haben wir die Faktoren oben festgelegt und dann unten wieder angepasst und dabei anscheinend was vergessen.
