### ISSUE TITLE
Nachträgliche Änderungen der Plugin-Settings ermöglichen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle_local_adele#300]
## Userstory ##
Als Administrator möchte ich auch nachträglich die Plugin-Eigenschaften ändern können, damit ich z.B. die berücksichtigten Kursbereiche erweitern kann.

## Anforderungen (objektiv & testbar) ##
- [ ] "Einstellungen" in der Plugin-Übersicht anbieten
![grafik](https://github.com/user-attachments/assets/16876048-2625-4939-8c50-74a11a5c77e0)

## Definition of Done ##
- [ ] Alle Anforderungen sind erfüllt
- [ ] Alle Anforderungen erfolgreich getestet
- [ ] Der Code ist übersichtlich strukturiert und mit Kommentaren versehen
- [ ] Nicht gebrauchte Code-Passagen sind entfernt
- [ ] Offene Punkte & Bugs in Tickets dokumentiert

**Comment by eynimeni** [comment]
Hi @ralferlebach 
es ist ja ohnehin möglich, die Pluginsettings jederzeit zu ändern, unabhängig von der aktuellen Version
unter ..../admin/search.php#linkmodules ist die Liste mit den Plugins und die Einstellungen können aufgerufen, verändert, gespeichert (!) werden
Das sollte die Funktion erfüllen, oder?

**Comment by ralferlebach** [comment]
Ahh ja, dann muss man unter Lokale Plugins schauen. Ich hatte nach AdeLe gesucht, nicht nach Lernpfad.
