### ISSUE TITLE
Mod Quiz completion

### ISSUE THREAD

**Issue by WunderJacob** [Wunderbyte-GmbH/moodle_local_adele#44]
- [x] Möglichkeit das Mod Quiz als completion criteria hinzuzufügen
- [x] Angabe eines notwendigen grades 
- [x] Berechnung der Completion 
- [ ] Angabe der Fragekategorie und Auswahl, wie viele Fragen aus einer gewissen Kategorie richtig gelöst werden mussten.

**Comment by eynimeni** [comment]
see #179
